name: Publish update
on:
  push:
    branches: [ main ]
defaults:
  tools:
    node: 22
jobs:
  update:
    name: Update
    type: update
    environment: production
    params:
      message: ${{ github.event.head_commit.message }}
      branch: production
